apiVersion: v1
kind: Secret
metadata:
  name: contract-kg-demo-secrets
  namespace: contract-kg-demo
type: Opaque
stringData:
  # ADMIN_PASSWORD: admin123
  # ADMIN_USER: admin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  WATSONX_API_KEY: your-api-key
