apiVersion: v1
kind: Service
metadata:
  name: fuseki
  namespace: contract-kg-demo
spec:
  selector:
    app: fuseki
  ports:
    - name: http
      port: 3030
      targetPort: 3030
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: contract-kg-demo
spec:
  selector:
    app: etcd
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: contract-kg-demo
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: contract-kg-demo
spec:
  selector:
    app: milvus
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix
  namespace: contract-kg-demo
spec:
  selector:
    app: phoenix
  ports:
    - name: http
      port: 6006
      targetPort: 6006

    - name: otlp-grpc
      port: 4317
      targetPort: 4317

    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: contract-kg-demo
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP  
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  namespace: contract-kg-demo
spec:
  selector:
    app: ingestion-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: retrieval-api
  namespace: contract-kg-demo
spec:
  selector:
    app: retrieval-api
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP            
---
apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: contract-kg-demo
spec:
  selector:
    app: attu
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP  
